### ISSUE TITLE
Escaping spec language interferes with reported line numbers

### ISSUE THREAD

**Issue by seizethedave** [uwplse/cozy#12]
That is, if I use 

```
{{
import "...";
}}
```

and get a syntax error later in the spec, the reported line number is off by approximately the number of lines occupied by the spec syntax escape.

**Comment by Calvin-L** [comment]
Ugh good point.

This is an instance of PLY's terrible interface. I think in `parse.py`, the `t_EXTERNCODETOKEN` rule needs to update `t.lexer.lineno` appropriately, like `t_newline` does.
